/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 24 16:45:19 GMT 2023
 */

package Agile.Software.Testing.LeanTesting;

import org.junit.Test;
import static org.junit.Assert.*;
import Agile.Software.Testing.LeanTesting.Multi;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Multi_ESTest extends Multi_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Multi multi0 = new Multi();
      int int0 = multi0.multi(0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Multi multi0 = new Multi();
      int int0 = multi0.multi(2676496);
      assertEquals((-374611712), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Multi multi0 = new Multi();
      int int0 = multi0.multi(1636);
      assertEquals(2676496, int0);
  }
}
