/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 24 09:37:35 GMT 2023
 */

package Agile.Software.Testing.LeanTesting;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Agile.Software.Testing.LeanTesting.Sum;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Sum_ESTest extends Sum_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Sum sum0 = new Sum();
      sum0.start = 0;
      sum0.start = 1;
      sum0.end = 1;
      Sum.sum(2527, 313);
      Sum.sum(1, (-1836));
      Sum.sum(0, 1876);
      Sum.sum(0, (-1));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Sum sum0 = new Sum();
      sum0.end = 0;
      sum0.start = 0;
      sum0.end = 0;
      sum0.start = 1;
      sum0.start = 0;
      sum0.start = 2505;
      sum0.end = 0;
      sum0.end = 0;
      sum0.end = (-372);
      int int0 = Sum.sum((-2358), (-2358));
      Sum.sum((-2358), (-2358));
      Sum.sum((-2358), (-2358));
      Sum.sum(2375, 0);
      Sum.sum(2505, (-2358));
      int int1 = (-2362);
      Sum.sum((-2362), (-2079));
      int int2 = 3116;
      Sum.sum(int0, int2);
      int int3 = 0;
      Sum.sum(int1, int3);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Sum sum0 = new Sum();
      sum0.start = (-1591);
      Sum.sum(709, 709);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Sum sum0 = new Sum();
      Sum.sum(1, 1);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Sum.sum((-1471), 0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Sum sum0 = new Sum();
      int int0 = 3018;
      sum0.end = 3018;
      int int1 = 2136;
      sum0.start = 3018;
      sum0.end = 2136;
      sum0.start = 1;
      sum0.start = 1;
      Sum.sum((-1714), 0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Sum.sum(1, 1);
      Sum sum0 = new Sum();
      sum0.start = 5021;
      sum0.start = 1;
      sum0.start = 1;
      sum0.end = 441;
      Sum.sum(1, 1);
      sum0.end = (-84);
      Sum.sum(1, (-1722));
      Sum.sum(699, 1);
      Sum.sum(1, 1);
      int int0 = Sum.sum(1, 446);
      assertEquals(99681, int0);
      
      int int1 = Sum.sum(1, (-1393));
      assertEquals((-1393), int1);
  }
}
